CREATE TABLE `BandwidthDown` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `Downloaded` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `BandwidthUp` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `Uploaded` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `DownstreamPowerLevel` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `PowerLevel1` float DEFAULT NULL,
  `PowerLevel2` float DEFAULT NULL,
  `PowerLevel3` float DEFAULT NULL,
  `PowerLevel4` float DEFAULT NULL,
  `PowerLevel5` float DEFAULT NULL,
  `PowerLevel6` float DEFAULT NULL,
  `PowerLevel7` float DEFAULT NULL,
  `PowerLevel8` float DEFAULT NULL,
  `PowerLevel9` float DEFAULT NULL,
  `PowerLevel10` float DEFAULT NULL,
  `PowerLevel11` float DEFAULT NULL,
  `PowerLevel12` float DEFAULT NULL,
  `PowerLevel13` float DEFAULT NULL,
  `PowerLevel14` float DEFAULT NULL,
  `PowerLevel15` float DEFAULT NULL,
  `PowerLevel16` float DEFAULT NULL,
  `PowerLevel17` float DEFAULT NULL,
  `PowerLevel18` float DEFAULT NULL,
  `PowerLevel19` float DEFAULT NULL,
  `PowerLevel20` float DEFAULT NULL,
  `PowerLevel21` float DEFAULT NULL,
  `PowerLevel22` float DEFAULT NULL,
  `PowerLevel23` float DEFAULT NULL,
  `PowerLevel24` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `Latencies` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `Protocol` varchar(4) NOT NULL,
  `TTL` tinyint(3) unsigned NOT NULL,
  `Min` float DEFAULT NULL,
  `Avg` float DEFAULT NULL,
  `Max` float DEFAULT NULL,
  `Loss` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx1` (`Protocol`,`TTL`,`time`)
);

CREATE TABLE `PostRSErrors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `PostRSErrors1` int(11) DEFAULT NULL,
  `PostRSErrors2` int(11) DEFAULT NULL,
  `PostRSErrors3` int(11) DEFAULT NULL,
  `PostRSErrors4` int(11) DEFAULT NULL,
  `PostRSErrors5` int(11) DEFAULT NULL,
  `PostRSErrors6` int(11) DEFAULT NULL,
  `PostRSErrors7` int(11) DEFAULT NULL,
  `PostRSErrors8` int(11) DEFAULT NULL,
  `PostRSErrors9` int(11) DEFAULT NULL,
  `PostRSErrors10` int(11) DEFAULT NULL,
  `PostRSErrors11` int(11) DEFAULT NULL,
  `PostRSErrors12` int(11) DEFAULT NULL,
  `PostRSErrors13` int(11) DEFAULT NULL,
  `PostRSErrors14` int(11) DEFAULT NULL,
  `PostRSErrors15` int(11) DEFAULT NULL,
  `PostRSErrors16` int(11) DEFAULT NULL,
  `PostRSErrors17` int(11) DEFAULT NULL,
  `PostRSErrors18` int(11) DEFAULT NULL,
  `PostRSErrors19` int(11) DEFAULT NULL,
  `PostRSErrors20` int(11) DEFAULT NULL,
  `PostRSErrors21` int(11) DEFAULT NULL,
  `PostRSErrors22` int(11) DEFAULT NULL,
  `PostRSErrors23` int(11) DEFAULT NULL,
  `PostRSErrors24` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `PreRSErrors` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `PreRSErrors1` int(11) DEFAULT NULL,
  `PreRSErrors2` int(11) DEFAULT NULL,
  `PreRSErrors3` int(11) DEFAULT NULL,
  `PreRSErrors4` int(11) DEFAULT NULL,
  `PreRSErrors5` int(11) DEFAULT NULL,
  `PreRSErrors6` int(11) DEFAULT NULL,
  `PreRSErrors7` int(11) DEFAULT NULL,
  `PreRSErrors8` int(11) DEFAULT NULL,
  `PreRSErrors9` int(11) DEFAULT NULL,
  `PreRSErrors10` int(11) DEFAULT NULL,
  `PreRSErrors11` int(11) DEFAULT NULL,
  `PreRSErrors12` int(11) DEFAULT NULL,
  `PreRSErrors13` int(11) DEFAULT NULL,
  `PreRSErrors14` int(11) DEFAULT NULL,
  `PreRSErrors15` int(11) DEFAULT NULL,
  `PreRSErrors16` int(11) DEFAULT NULL,
  `PreRSErrors17` int(11) DEFAULT NULL,
  `PreRSErrors18` int(11) DEFAULT NULL,
  `PreRSErrors19` int(11) DEFAULT NULL,
  `PreRSErrors20` int(11) DEFAULT NULL,
  `PreRSErrors21` int(11) DEFAULT NULL,
  `PreRSErrors22` int(11) DEFAULT NULL,
  `PreRSErrors23` int(11) DEFAULT NULL,
  `PreRSErrors24` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `RxMER` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `RxMER1` float DEFAULT NULL,
  `RxMER2` float DEFAULT NULL,
  `RxMER3` float DEFAULT NULL,
  `RxMER4` float DEFAULT NULL,
  `RxMER5` float DEFAULT NULL,
  `RxMER6` float DEFAULT NULL,
  `RxMER7` float DEFAULT NULL,
  `RxMER8` float DEFAULT NULL,
  `RxMER9` float DEFAULT NULL,
  `RxMER10` float DEFAULT NULL,
  `RxMER11` float DEFAULT NULL,
  `RxMER12` float DEFAULT NULL,
  `RxMER13` float DEFAULT NULL,
  `RxMER14` float DEFAULT NULL,
  `RxMER15` float DEFAULT NULL,
  `RxMER16` float DEFAULT NULL,
  `RxMER17` float DEFAULT NULL,
  `RxMER18` float DEFAULT NULL,
  `RxMER19` float DEFAULT NULL,
  `RxMER20` float DEFAULT NULL,
  `RxMER21` float DEFAULT NULL,
  `RxMER22` float DEFAULT NULL,
  `RxMER23` float DEFAULT NULL,
  `RxMER24` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `UpstreamPowerLevel` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime NOT NULL,
  `DeviceName` varchar(255) NOT NULL,
  `PowerLevel1` float DEFAULT NULL,
  `PowerLevel2` float DEFAULT NULL,
  `PowerLevel3` float DEFAULT NULL,
  `PowerLevel4` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx1` (`DeviceName`,`time`)
);

CREATE TABLE `APC` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `time` datetime DEFAULT NULL,
  `APC` varchar(12) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `HOSTNAME` varchar(255) DEFAULT NULL,
  `VERSION` varchar(255) DEFAULT NULL,
  `UPSNAME` varchar(255) DEFAULT NULL,
  `CABLE` varchar(255) DEFAULT NULL,
  `DRIVER` varchar(255) DEFAULT NULL,
  `UPSMODE` varchar(255) DEFAULT NULL,
  `STARTTIME` datetime DEFAULT NULL,
  `MODEL` varchar(255) DEFAULT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `LINEV` float DEFAULT NULL,
  `LOADPCT` float DEFAULT NULL,
  `BCHARGE` float DEFAULT NULL,
  `TIMELEFT` float DEFAULT NULL,
  `MBATTCHG` float DEFAULT NULL,
  `MINTIMEL` int(11) DEFAULT NULL,
  `MAXTIME` int(11) DEFAULT NULL,
  `MAXLINEV` float DEFAULT NULL,
  `MINLINEV` float DEFAULT NULL,
  `OUTPUTV` float DEFAULT NULL,
  `SENSE` varchar(8) DEFAULT NULL,
  `DWAKE` int(11) DEFAULT NULL,
  `DSHUTD` int(11) DEFAULT NULL,
  `DLOWBATT` int(11) DEFAULT NULL,
  `LOTRANS` float DEFAULT NULL,
  `HITRANS` float DEFAULT NULL,
  `RETPCT` float DEFAULT NULL,
  `ITEMP` float DEFAULT NULL,
  `ALARMDEL` varchar(16) DEFAULT NULL,
  `BATTV` float DEFAULT NULL,
  `LINEFREQ` float DEFAULT NULL,
  `LASTXFER` varchar(255) DEFAULT NULL,
  `NUMXFERS` int(11) DEFAULT NULL,
  `TONBATT` int(11) DEFAULT NULL,
  `CUMONBATT` int(11) DEFAULT NULL,
  `XOFFBATT` varchar(255) DEFAULT NULL,
  `SELFTEST` varchar(255) DEFAULT NULL,
  `STESTI` varchar(255) DEFAULT NULL,
  `STATFLAG` varchar(16) DEFAULT NULL,
  `DIPSW` varchar(4) DEFAULT NULL,
  `REG1` varchar(4) DEFAULT NULL,
  `REG2` varchar(4) DEFAULT NULL,
  `REG3` varchar(4) DEFAULT NULL,
  `MANDATE` date DEFAULT NULL,
  `SERIALNO` varchar(12) DEFAULT NULL,
  `BATTDATE` date DEFAULT NULL,
  `NOMOUTV` float DEFAULT NULL,
  `NOMBATTV` float DEFAULT NULL,
  `EXTBATTS` int(11) DEFAULT NULL,
  `FIRMWARE` varchar(10) DEFAULT NULL,
  `END_APC` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx1` (`time`)
);
