{
 "title": "Bandwidth and Latency (SuperHub 2ac)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          LEAST(ABS(Uploaded - LAG(Uploaded, 1) OVER (ORDER BY `time` ASC)), Uploaded) / (UNIX_TIMESTAMP(`time`) - LAG(UNIX_TIMESTAMP(`time`), 1) OVER (ORDER BY `time` ASC)) as value,\n          'Upstream' as metric\nFROM      BandwidthUp\nWHERE     DeviceName = 'SH2ac' and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          LEAST(ABS(Downloaded - LAG(Downloaded, 1) OVER (ORDER BY `time` ASC)), Downloaded) / (UNIX_TIMESTAMP(`time`) - LAG(UNIX_TIMESTAMP(`time`), 1) OVER (ORDER BY `time` ASC)) as value,\n          'Downstream' as metric\nFROM      BandwidthDown\nWHERE     DeviceName = 'SH2ac' and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    }
   ]
  },
  {
   "title": "TCP Latency TTL=13 (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Max` as value,\n          'Maximum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'TCP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Avg` as value,\n          'Average' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'TCP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Min` as value,\n          'Minimum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'TCP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Loss` * (-1) as value,\n          'Loss' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'TCP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    }
   ]
  },
  {
   "title": "ICMP Latency TTL=13 (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Max` as value,\n          'Maximum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Avg` as value,\n          'Average' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Min` as value,\n          'Minimum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Loss` * (-1) as value,\n          'Loss' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 13 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    }
   ]
  },
  {
   "title": "ICMP Latency TTL=3 (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Max` as value,\n          'Maximum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 3 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Avg` as value,\n          'Average' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 3 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Min` as value,\n          'Minimum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 3 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Loss` * (-1) as value,\n          'Loss' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 3 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    }
   ]
  },
  {
   "title": "ICMP Latency TTL=1 (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Max` as value,\n          'Maximum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 1 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Avg` as value,\n          'Average' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 1 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Min` as value,\n          'Minimum' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 1 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    },
    {
     "rawSql": "SELECT    UNIX_TIMESTAMP(`time`) as `time`,\n          `Loss` * (-1) as value,\n          'Loss' as metric\nFROM      Latencies\nWHERE     DeviceName = 'SH2ac' and\n          Protocol = 'ICMP' and\n          TTL = 1 and\n          $__timeFilter(`time`)\nORDER BY  `time` ASC"
    }
   ]
  }
 ]
}