{
 "title": "Power",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Line Voltage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         LINEV as value,\n         'Line Voltage' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    },
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         MINLINEV as value,\n         'Minimum Line Voltage' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    },
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         MAXLINEV as value,\n         'Mximum Line Voltage' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    },
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         OUTPUTV as value,\n         'Output Voltage' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         LINEFREQ as value,\n         'Line Frequency' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    }
   ]
  },
  {
   "title": "UPS Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         ITEMP as value,\n         'Internal Temperature' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT   UNIX_TIMESTAMP(`time`) as time_sec,\n         LOADPCT as value,\n         'UPS Load' as metric\nFROM     APC\nWHERE    $__timeFilter(`time`)\nORDER BY `time` ASC\n"
    }
   ]
  }
 ]
}